const PRODUCT_IMAGES = {
  laptop: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80",
  laptopSilver: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=80",
  laptopGaming: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=900&q=80",
  phone: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80",
  iphone: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=900&q=80",
  speaker: "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=900&q=80",
  headphonesDark: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80",
  headphonesWhite: "https://images.unsplash.com/photo-1524678606370-a47ad25cb82a?auto=format&fit=crop&w=900&q=80",
  headphonesRed: "https://images.unsplash.com/photo-1487215078519-e21cc028cb29?auto=format&fit=crop&w=900&q=80",
  earbudsWhite: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=900&q=80",
  earbudsGraphite: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=900&q=80",
  earphonesWire: "https://images.unsplash.com/photo-1491927570842-0261e477d937?auto=format&fit=crop&w=900&q=80",
  mouse: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=900&q=80",
  keyboard: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80",
  hub: "https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=900&q=80",
  charger: "https://images.unsplash.com/photo-1603539444875-76e7684265f6?auto=format&fit=crop&w=900&q=80",
  cableUsbC: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=900&q=80",
  cableLightning: "https://images.unsplash.com/photo-1603539444875-76e7684265f6?auto=format&fit=crop&w=900&q=80",
  cableBraided: "https://images.unsplash.com/photo-1603539444875-76e7684265f6?auto=format&fit=crop&w=900&q=80",
  desk: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80",
  lamp: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80",
  fanDesk: "https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&w=900&q=80",
  fanStanding: "https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&w=900&q=80",
  fanNeck: "https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&w=900&q=80",
  fanPad: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=900&q=80",
  watch: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80",
  camera: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=80",
  tablet: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=900&q=80",
  monitor: "https://images.unsplash.com/photo-1586210579191-33b45e38fa2c?auto=format&fit=crop&w=900&q=80",
  printer: "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa4?auto=format&fit=crop&w=900&q=80",
  router: "https://images.unsplash.com/photo-1544428576-d3440c9e7c8b?auto=format&fit=crop&w=900&q=80",
  projector: "https://images.unsplash.com/photo-1530878902700-5bdc4b7c2e44?auto=format&fit=crop&w=900&q=80",
  webcam: "https://images.unsplash.com/photo-1587826080309-3840eed545bc?auto=format&fit=crop&w=900&q=80",
  gamepad: "https://images.unsplash.com/photo-1593305841991-05c297ba4575?auto=format&fit=crop&w=900&q=80",
  smartwatch: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=900&q=80",
  vrheadset: "https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?auto=format&fit=crop&w=900&q=80",
  microphone: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=900&q=80",
  server: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=900&q=80",
  nas: "https://images.unsplash.com/photo-1531123414780-f74242c2b052?auto=format&fit=crop&w=900&q=80",
  earbudsPro: "https://images.unsplash.com/photo-1590658268037-6bf12f032f55?auto=format&fit=crop&w=900&q=80",
  phoneFlip: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&w=900&q=80",
  earbudsTWS: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=900&q=80",
  powerStation: "https://images.unsplash.com/photo-1642367340318-96fdbc5d6215?auto=format&fit=crop&w=900&q=80",
  lightStrip: "https://images.unsplash.com/photo-1550985543-f1b2af1d0a2a?auto=format&fit=crop&w=900&q=80",
  driveSSD: "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=900&q=80",
};

const laptopRows = [
  ["HP 250 G9", "HP", "Core i3 12th Gen, 8GB RAM, 256GB SSD, 15.6-inch display", 3350, "laptop"],
  ["HP Pavilion 15", "HP", "Core i5 12th Gen, 8GB RAM, 512GB SSD, Windows 11", 6850, "laptop"],
  ["HP Envy x360 13", "HP", "Ryzen 5, 16GB RAM, 512GB SSD, touch convertible display", 8900, "laptopSilver"],
  ["HP EliteBook 840 G8", "HP", "Core i5, 16GB RAM, 512GB SSD, business security features", 6100, "laptopSilver"],
  ["HP ProBook 450 G9", "HP", "Core i5 12th Gen, 16GB RAM, 512GB SSD, 15.6-inch display", 7200, "laptop"],
  ["HP Spectre x360 14", "HP", "Core i7, 16GB RAM, 1TB SSD, 2.8K OLED touch display", 14500, "laptopSilver"],
  ["HP Victus 15 Gaming", "HP", "Core i5, 16GB RAM, RTX graphics, 512GB SSD, 144Hz screen", 9800, "laptopGaming"],
  ["Dell Latitude 5420", "Dell", "Core i5, 16GB RAM, 512GB SSD, business-grade chassis", 5200, "laptop"],
  ["Dell Latitude 7490", "Dell", "Core i7, 16GB RAM, 512GB SSD, backlit keyboard", 4700, "laptop"],
  ["Dell Inspiron 15 3520", "Dell", "Core i5 12th Gen, 8GB RAM, 512GB SSD, full HD display", 5600, "laptop"],
  ["Dell XPS 13", "Dell", "Core i7, 16GB RAM, 512GB SSD, premium ultrabook display", 11200, "laptopSilver"],
  ["Dell G15 Gaming", "Dell", "Core i7, 16GB RAM, RTX graphics, 512GB SSD, 120Hz screen", 11800, "laptopGaming"],
  ["Dell XPS 15", "Dell", "Core i7, 16GB RAM, 512GB SSD, OLED 3.5K display", 16200, "laptopSilver"],
  ["Dell Precision 3570", "Dell", "Core i7, 32GB RAM, 512GB SSD, workstation-grade mobile", 14200, "laptop"],
  ["Lenovo ThinkPad T480", "Lenovo", "Core i5, 8GB RAM, 256GB SSD, durable business keyboard", 3900, "laptop"],
  ["Lenovo ThinkPad T14", "Lenovo", "Core i5 11th Gen, 16GB RAM, 512GB SSD, fingerprint reader", 6500, "laptop"],
  ["Lenovo IdeaPad 3", "Lenovo", "Ryzen 5, 8GB RAM, 512GB SSD, 15.6-inch full HD screen", 4300, "laptop"],
  ["Lenovo IdeaPad Slim 5", "Lenovo", "Core i5 13th Gen, 16GB RAM, 512GB SSD, slim metal finish", 7600, "laptopSilver"],
  ["Lenovo Legion 5", "Lenovo", "Ryzen 7, 16GB RAM, RTX graphics, 1TB SSD, gaming display", 14900, "laptopGaming"],
  ["Lenovo ThinkPad X1 Carbon", "Lenovo", "Core i7, 16GB RAM, 512GB SSD, ultra-light carbon body", 17200, "laptopSilver"],
  ["Lenovo Yoga 7i", "Lenovo", "Core i5, 16GB RAM, 512GB SSD, 2-in-1 touch convertible", 8200, "laptopSilver"],
  ["Acer Aspire 5", "Acer", "Core i3, 8GB RAM, 256GB SSD, student-friendly laptop", 3650, "laptopSilver"],
  ["Acer Swift 3", "Acer", "Core i5, 8GB RAM, 512GB SSD, lightweight metal body", 5800, "laptopSilver"],
  ["Acer Nitro 5", "Acer", "Core i5, 16GB RAM, RTX graphics, 512GB SSD, RGB keyboard", 9600, "laptopGaming"],
  ["Acer TravelMate P2", "Acer", "Core i5, 8GB RAM, 512GB SSD, office productivity laptop", 5100, "laptop"],
  ["Acer Chromebook Spin", "Acer", "ChromeOS, 8GB RAM, 128GB storage, touchscreen convertible", 3400, "laptopSilver"],
  ["Acer Predator Helios 16", "Acer", "Core i7, 32GB RAM, RTX graphics, 1TB SSD, 240Hz display", 21500, "laptopGaming"],
  ["Asus Vivobook 14", "Asus", "Core i5, 8GB RAM, 512GB SSD, slim everyday laptop", 4300, "laptop"],
  ["Asus ZenBook 14 OLED", "Asus", "Core i7, 16GB RAM, 1TB SSD, OLED display", 11800, "laptopSilver"],
  ["Asus TUF Gaming F15", "Asus", "Core i7, 16GB RAM, RTX graphics, 512GB SSD, 144Hz screen", 12600, "laptopGaming"],
  ["Asus ExpertBook B1", "Asus", "Core i5, 8GB RAM, 512GB SSD, business laptop", 5900, "laptop"],
  ["Asus ROG Strix G16", "Asus", "Core i9, 16GB RAM, RTX graphics, 1TB SSD, gaming chassis", 21500, "laptopGaming"],
  ["Asus Vivobook Pro 15", "Asus", "Ryzen 7, 16GB RAM, RTX graphics, 512GB SSD, creator display", 13200, "laptopGaming"],
  ["MacBook Air M1", "Apple", "Apple M1, 8GB memory, 256GB SSD, 13-inch Retina display", 9400, "laptopSilver"],
  ["MacBook Air M2", "Apple", "Apple M2, 8GB memory, 256GB SSD, MagSafe charging", 13200, "laptopSilver"],
  ["MacBook Pro 13 M2", "Apple", "Apple M2, 8GB memory, 512GB SSD, Retina display", 15600, "laptopSilver"],
  ["MacBook Pro 14", "Apple", "Apple silicon Pro chip, 16GB memory, 512GB SSD, Liquid Retina XDR", 18500, "laptopSilver"],
  ["MacBook Pro 16", "Apple", "Apple silicon Pro chip, 16GB memory, 1TB SSD, 16-inch display", 24500, "laptopSilver"],
  ["MacBook Air M3", "Apple", "Apple M3, 8GB memory, 256GB SSD, 13.6-inch Liquid Retina", 15500, "laptopSilver"],
  ["Microsoft Surface Laptop 4", "Microsoft", "Core i5, 8GB RAM, 512GB SSD, touchscreen display", 7800, "laptopSilver"],
  ["Microsoft Surface Pro 8", "Microsoft", "Core i5, 8GB RAM, 256GB SSD, detachable touchscreen", 8600, "laptopSilver"],
  ["Microsoft Surface Laptop Go", "Microsoft", "Core i5, 8GB RAM, 256GB SSD, compact touchscreen", 5200, "laptopSilver"],
  ["Microsoft Surface Book 3", "Microsoft", "Core i7, 16GB RAM, 512GB SSD, detachable GPU base", 16800, "laptopSilver"],
  ["MSI Modern 14", "MSI", "Core i5, 8GB RAM, 512GB SSD, lightweight productivity laptop", 6100, "laptopSilver"],
  ["MSI GF63 Thin", "MSI", "Core i5, 16GB RAM, GTX graphics, 512GB SSD, gaming-ready", 8500, "laptopGaming"],
  ["MSI Katana 15", "MSI", "Core i7, 16GB RAM, RTX graphics, 1TB SSD, 144Hz display", 13800, "laptopGaming"],
  ["MSI Stealth 14 Studio", "MSI", "Core i7, 32GB RAM, RTX graphics, 1TB SSD, QHD 240Hz", 19800, "laptopGaming"],
  ["Samsung Galaxy Book2", "Samsung", "Core i5, 8GB RAM, 512GB SSD, AMOLED-style thin design", 7600, "laptopSilver"],
  ["Samsung Galaxy Book Pro", "Samsung", "Core i7, 16GB RAM, 512GB SSD, lightweight premium build", 9800, "laptopSilver"],
  ["Samsung Galaxy Book3 Ultra", "Samsung", "Core i7, 16GB RAM, RTX graphics, 1TB SSD, AMOLED display", 19500, "laptopGaming"],
  ["Huawei MateBook D15", "Huawei", "Core i5, 8GB RAM, 512GB SSD, metal chassis", 5600, "laptopSilver"],
  ["Huawei MateBook X Pro", "Huawei", "Core i7, 16GB RAM, 1TB SSD, premium display", 14200, "laptopSilver"],
  ["Razer Blade 15", "Razer", "Core i7, 16GB RAM, RTX graphics, 1TB SSD, 144Hz panel", 22500, "laptopGaming"],
  ["Razer Blade 14", "Razer", "Ryzen 9, 16GB RAM, RTX graphics, 1TB SSD, QHD 165Hz", 19800, "laptopGaming"],
  ["Alienware m15", "Alienware", "Core i7, 16GB RAM, RTX graphics, 1TB SSD, high-refresh screen", 23800, "laptopGaming"],
  ["Alienware x16", "Alienware", "Core i9, 32GB RAM, RTX graphics, 1TB SSD, 240Hz OLED", 29500, "laptopGaming"],
  ["Gigabyte G5", "Gigabyte", "Core i5, 16GB RAM, RTX graphics, 512GB SSD, gaming display", 10200, "laptopGaming"],
  ["Gigabyte Aorus 15", "Gigabyte", "Core i7, 16GB RAM, RTX graphics, 1TB SSD, 165Hz display", 14200, "laptopGaming"],
  ["LG Gram 16", "LG", "Core i7, 16GB RAM, 1TB SSD, ultra-light 16-inch body", 15400, "laptopSilver"],
  ["LG Gram 14", "LG", "Core i5, 8GB RAM, 512GB SSD, ultra-light compact body", 11200, "laptopSilver"],
  ["Toshiba Dynabook Tecra", "Dynabook", "Core i5, 8GB RAM, 256GB SSD, business laptop", 4100, "laptop"],
  ["Fujitsu Lifebook U7411", "Fujitsu", "Core i5, 16GB RAM, 512GB SSD, enterprise security", 5400, "laptop"],
  ["Chuwi HeroBook Pro", "Chuwi", "Intel N-series, 8GB RAM, 256GB SSD, entry productivity", 2200, "laptop"],
  ["Avita Liber V", "Avita", "Core i5, 8GB RAM, 512GB SSD, colorful slim laptop", 3800, "laptopSilver"],
  ["Gateway Ultra Slim 14", "Gateway", "Core i3, 8GB RAM, 256GB SSD, student laptop", 2950, "laptop"],
  ["NexBook Air 14", "NexBook", "Intel N100, 8GB RAM, 256GB SSD, lightweight study laptop", 2600, "laptopSilver"],
  ["Google Pixelbook Go", "Google", "Core i5, 8GB RAM, 128GB SSD, ChromeOS, lightweight", 5200, "laptopSilver"],
  ["OnePlus Book", "OnePlus", "Core i5, 8GB RAM, 512GB SSD, aluminium body, USB-C", 6100, "laptopSilver"],
  ["VAIO SX14", "VAIO", "Core i7, 16GB RAM, 512GB SSD, premium Japanese ultrabook", 14800, "laptopSilver"],
  ["Honor MagicBook 14", "Honor", "Ryzen 5, 8GB RAM, 512GB SSD, slim metal body", 5200, "laptopSilver"],
  ["Xiaomi Mi Notebook Pro", "Xiaomi", "Core i5, 8GB RAM, 512GB SSD, 15.6-inch display", 4400, "laptopSilver"],
  ["Panasonic Toughbook CF-54", "Panasonic", "Core i5, 8GB RAM, 256GB SSD, rugged business", 8200, "laptop"],
];

const phoneRows = [
  ["Samsung Galaxy A05s", "Samsung", "128GB storage, 4GB RAM, 50MP camera, 5000mAh battery", 1650, "phone"],
  ["Samsung Galaxy A15", "Samsung", "128GB storage, 6GB RAM, AMOLED display, 5000mAh battery", 2350, "phone"],
  ["Samsung Galaxy A25", "Samsung", "128GB storage, 5G support, Super AMOLED display, 50MP camera", 3100, "phone"],
  ["Samsung Galaxy A35", "Samsung", "256GB storage, 8GB RAM, AMOLED display, IP-rated body", 3900, "phone"],
  ["Samsung Galaxy A55", "Samsung", "256GB storage, AMOLED display, long battery life, 5G support", 4750, "phone"],
  ["Samsung Galaxy S21", "Samsung", "128GB storage, flagship camera, 120Hz display, 5G", 5200, "phone"],
  ["Samsung Galaxy S22", "Samsung", "128GB storage, flagship processor, AMOLED display, 5G", 6900, "phone"],
  ["Samsung Galaxy S23", "Samsung", "256GB storage, premium camera, AMOLED 120Hz display, 5G", 9800, "phone"],
  ["Samsung Galaxy S24", "Samsung", "256GB storage, AI features, 120Hz AMOLED, 5G, 7yr updates", 12500, "phone"],
  ["Samsung Galaxy S24 Ultra", "Samsung", "512GB storage, S Pen, titanium body, 200MP camera", 18200, "phone"],
  ["Samsung Galaxy Z Flip 4", "Samsung", "256GB storage, foldable display, compact design, 5G", 8400, "phone"],
  ["Samsung Galaxy Z Flip 5", "Samsung", "256GB storage, larger cover screen, flex mode, 5G", 10200, "phoneFlip"],
  ["Samsung Galaxy Z Fold 4", "Samsung", "256GB storage, foldable tablet display, multitasking power", 15600, "phone"],
  ["Samsung Galaxy Z Fold 5", "Samsung", "512GB storage, lighter hinge, powerful multitasking", 18200, "phone"],
  ["iPhone XR", "Apple", "64GB storage, Face ID, 6.1-inch display, single rear camera", 3200, "iphone"],
  ["iPhone 11", "Apple", "128GB storage, dual camera, Face ID, iOS support", 4500, "iphone"],
  ["iPhone 12 Mini", "Apple", "64GB storage, compact OLED display, 5G, Face ID", 4100, "iphone"],
  ["iPhone 12 Pro", "Apple", "128GB storage, triple camera, OLED display, 5G", 6500, "iphone"],
  ["iPhone 13", "Apple", "128GB storage, dual camera, OLED display, strong battery life", 7900, "iphone"],
  ["iPhone 13 Pro", "Apple", "256GB storage, Pro camera, 120Hz display, 5G", 9800, "iphone"],
  ["iPhone 14", "Apple", "128GB storage, dual camera, OLED display, emergency features", 9600, "iphone"],
  ["iPhone 14 Pro", "Apple", "256GB storage, Pro camera, Dynamic Island, 5G", 11800, "iphone"],
  ["iPhone 15", "Apple", "128GB storage, USB-C, improved camera, OLED display", 12800, "iphone"],
  ["iPhone 15 Pro Max", "Apple", "256GB storage, titanium body, Pro camera, USB-C", 17800, "iphone"],
  ["iPhone SE 3rd Gen", "Apple", "64GB storage, A15 chip, Touch ID, compact design", 5200, "iphone"],
  ["Tecno Spark 20", "Tecno", "256GB storage, 8GB RAM, 50MP camera, 5000mAh battery", 1750, "phone"],
  ["Tecno Spark 20 Pro", "Tecno", "256GB storage, 8GB RAM, 108MP camera, 5000mAh battery", 2050, "phone"],
  ["Tecno Camon 20", "Tecno", "256GB storage, AMOLED display, 64MP camera, fast charging", 2350, "phone"],
  ["Tecno Camon 30", "Tecno", "256GB storage, camera-focused sensor, AMOLED display, USB-C", 2850, "phone"],
  ["Tecno Pova 6", "Tecno", "256GB storage, large battery, gaming-focused display, fast charging", 3300, "phone"],
  ["Tecno Phantom X2", "Tecno", "256GB storage, curved AMOLED, 64MP main camera, 5G", 4800, "phone"],
  ["Infinix Smart 8", "Infinix", "64GB storage, 4GB RAM, large battery, Android", 1100, "phone"],
  ["Infinix Hot 40i", "Infinix", "128GB storage, 8GB RAM expansion, 50MP camera", 1550, "phone"],
  ["Infinix Hot 40 Pro", "Infinix", "256GB storage, 8GB RAM, 120Hz display, fast charging", 2200, "phone"],
  ["Infinix Note 30", "Infinix", "256GB storage, JBL-tuned speakers, 45W charging", 2150, "phone"],
  ["Infinix Note 40", "Infinix", "256GB storage, AMOLED display, fast charging, long battery", 2450, "phone"],
  ["Infinix Zero 30", "Infinix", "256GB storage, 108MP camera, AMOLED 120Hz, 5G", 3200, "phone"],
  ["Google Pixel 6a", "Google", "128GB storage, Tensor chip, clean Android, great camera", 3900, "phone"],
  ["Google Pixel 7", "Google", "128GB storage, Tensor G2, excellent camera software, 5G", 6200, "phone"],
  ["Google Pixel 7 Pro", "Google", "256GB storage, telephoto camera, high-refresh OLED, 5G", 8200, "phone"],
  ["Google Pixel 8", "Google", "128GB storage, Tensor G3, AI camera tools, 5G", 9800, "phone"],
  ["Google Pixel 8 Pro", "Google", "256GB storage, Pro camera system, OLED display, 5G", 13200, "phone"],
  ["Google Pixel 9", "Google", "128GB storage, Tensor G4, AI features, 5G", 11500, "phone"],
  ["Oppo A58", "Oppo", "128GB storage, 6GB RAM, 50MP camera, 5000mAh battery", 2100, "phone"],
  ["Oppo A78", "Oppo", "256GB storage, AMOLED display, fast charging, slim build", 2950, "phone"],
  ["Oppo Reno 8", "Oppo", "256GB storage, camera-focused design, AMOLED screen, 5G", 4200, "phone"],
  ["Oppo Reno 10", "Oppo", "256GB storage, portrait camera, fast charging, AMOLED display", 5400, "phone"],
  ["Oppo Find X5", "Oppo", "256GB storage, flagship camera, premium display, 5G", 7600, "phone"],
  ["Oppo Find N2 Flip", "Oppo", "256GB storage, foldable flip, Hasselblad camera, 5G", 10800, "phoneFlip"],
  ["Redmi 12", "Xiaomi", "128GB storage, 4GB RAM, large display, 5000mAh battery", 1650, "phone"],
  ["Redmi Note 12", "Xiaomi", "128GB storage, AMOLED display, 5000mAh battery, USB-C", 2350, "phone"],
  ["Redmi Note 13 Pro", "Xiaomi", "256GB storage, 8GB RAM, high-resolution camera, AMOLED", 3600, "phone"],
  ["Xiaomi 12 Lite", "Xiaomi", "256GB storage, slim body, AMOLED display, fast charging", 4300, "phone"],
  ["Xiaomi 13T", "Xiaomi", "256GB storage, flagship display, Leica-style camera system", 6900, "phone"],
  ["Xiaomi 14", "Xiaomi", "256GB storage, Snapdragon 8 Gen 3, Leica cameras, 5G", 8800, "phone"],
  ["Xiaomi 14 Ultra", "Xiaomi", "512GB storage, Leica quad camera, premium build", 12800, "phone"],
  ["Vivo Y27", "Vivo", "128GB storage, 6GB RAM, 5000mAh battery, fast charging", 1950, "phone"],
  ["Vivo V25", "Vivo", "256GB storage, selfie-focused camera, AMOLED display", 3400, "phone"],
  ["Vivo X90 Pro", "Vivo", "256GB storage, Zeiss camera, flagship chip, 5G", 9200, "phone"],
  ["Honor X8a", "Honor", "128GB storage, 100MP camera, slim body, large display", 2500, "phone"],
  ["Honor 90", "Honor", "256GB storage, 200MP camera, curved AMOLED, 5G", 5200, "phone"],
  ["Itel S24", "Itel", "128GB storage, 8GB RAM expansion, 108MP camera, Android", 2050, "phone"],
  ["Itel A70", "Itel", "128GB storage, 4GB RAM, large battery, entry smartphone", 1250, "phone"],
  ["Nokia G60", "Nokia", "128GB storage, 5G support, clean Android, durable build", 2950, "phone"],
  ["Nokia X30", "Nokia", "256GB storage, PureView camera, eco-friendly body", 4200, "phone"],
  ["OnePlus Nord CE3", "OnePlus", "128GB storage, 8GB RAM, AMOLED display, 5G", 3800, "phone"],
  ["OnePlus 12", "OnePlus", "256GB storage, Snapdragon 8 Gen 3, Hasselblad camera, 5G", 11500, "phone"],
  ["Nothing Phone 2", "Nothing", "256GB storage, Glyph interface, 50MP dual camera, 5G", 7200, "phone"],
  ["Asus Zenfone 10", "Asus", "256GB storage, compact flagship, gimbal camera, 5G", 6900, "phone"],
  ["Sony Xperia 1 V", "Sony", "256GB storage, 4K OLED, flagship camera, 5G", 12800, "phone"],
  ["Motorola Edge 40", "Motorola", "256GB storage, curved AMOLED, IP68, 5G", 5200, "phone"],
  ["Realme 11 Pro", "Realme", "256GB storage, 8GB RAM, 100MP camera, AMOLED display", 3200, "phone"],
  ["Realme GT 3", "Realme", "256GB storage, 240W charging, flagship chip, 5G", 6500, "phone"],
];

const accessoryRows = [
  ["JBL Flip Style Speaker", "Audio", "Speakers", "Bluetooth speaker, waterproof-style body, 12-hour battery, USB-C", 920, "speaker"],
  ["JBL Charge 5 Style Speaker", "Audio", "Speakers", "Powerful Bluetooth speaker, deep bass, 20-hour battery, IP67", 1800, "speaker"],
  ["Marshall Emberton Style Speaker", "Audio", "Speakers", "Portable Bluetooth speaker, rugged build, stereo sound, USB-C", 3200, "speaker"],
  ["BassDock Party Speaker", "Audio", "Speakers", "Large Bluetooth speaker, deep bass, microphone input, LED lighting", 2100, "speaker"],
  ["Mini Boom Bluetooth Speaker", "Audio", "Speakers", "Compact speaker, Bluetooth, strap loop, USB charging", 260, "speaker"],
  ["Conference USB Speakerphone", "Audio", "Speakers", "360-degree microphone, USB connection, meeting controls, compact body", 980, "speaker"],
  ["SonicMax Wireless Headphones", "Audio", "Headphones", "Over-ear Bluetooth headphones, built-in microphone, foldable body", 680, "headphonesDark"],
  ["Sony WH-CH720N Style Headphones", "Audio", "Headphones", "Wireless ANC headphones, USB-C charging, long battery, app controls", 2550, "headphonesWhite"],
  ["NoiseShield ANC Headphones", "Audio", "Headphones", "Active noise cancelling, over-ear cushions, travel case, Bluetooth", 1250, "headphonesRed"],
  ["Bose QuietComfort Style Headphones", "Audio", "Headphones", "Premium ANC, comfortable fit, 24-hour battery, balanced sound", 4200, "headphonesWhite"],
  ["Studio Monitor Headphones", "Audio", "Headphones", "Closed-back studio headphones, flat response, coiled cable, pro-grade", 1800, "headphonesDark"],
  ["Gaming RGB Headset", "Audio", "Gaming Audio", "Boom microphone, RGB lighting, padded cups, 3.5mm and USB support", 620, "headphonesRed"],
  ["AirPod Pro Style Earbuds", "Audio", "Earbuds", "ANC earbuds, wireless case, touch controls, clear call microphones", 2100, "earbudsWhite"],
  ["Oraimo FreePods Pro", "Audio", "Earbuds", "Wireless earpiece, ANC mode, charging case, low-latency mode", 680, "earbudsGraphite"],
  ["StudioPod Wireless Earbuds", "Audio", "Earbuds", "Compact charging case, clear calls, touch controls, balanced sound", 480, "earbudsWhite"],
  ["Samsung Galaxy Buds2 Pro", "Audio", "Earbuds", "Hi-Fi sound, ANC, 360 audio, IPX7, wireless charging case", 2400, "earbudsGraphite"],
  ["SoundPeats True Wireless", "Audio", "Earbuds", "Low-latency earbuds, gaming mode, long battery, secure fit", 620, "earbudsPro"],
  ["JBL Tune Style Earphones", "Audio", "Earphones", "Wired earphones, in-line microphone, 3.5mm connector, bass tuning", 190, "earphonesWire"],
  ["USB-C Digital Earphones", "Audio", "Earphones", "USB-C earpiece, microphone, volume controls, no adapter needed", 220, "earphonesWire"],
  ["Clip-On Laptop Microphone", "Audio", "Microphones", "Lavalier microphone, plug-and-play cable, clear voice pickup", 140, "microphone"],
  ["USB Condenser Microphone", "Audio", "Microphones", "Studio condenser mic, cardioid pattern, volume knob, tripod stand", 580, "microphone"],
  ["SoundBar Mini", "Audio", "Speakers", "Desktop soundbar, USB powered, AUX input, low-profile design", 730, "speaker"],
  ["20,000mAh Power Bank", "Accessory", "Power & Charging", "20,000mAh capacity, dual USB output, LED indicator, fast charge", 420, "charger"],
  ["30,000mAh Fast Power Bank", "Accessory", "Power & Charging", "30,000mAh capacity, USB-C input, fast charging, torch", 620, "charger"],
  ["Solar Power Bank 30,000mAh", "Accessory", "Power & Charging", "Solar trickle charge, LED torch, USB-A and USB-C ports", 520, "charger"],
  ["60,000mAh Laptop Power Station", "Accessory", "Power & Charging", "AC output, USB-C PD, LED display, emergency backup power", 3600, "powerStation"],
  ["Portable Solar Generator 150W", "Accessory", "Power & Charging", "150W output, AC socket, DC port, USB-C, solar input", 3950, "powerStation"],
  ["65W USB-C Laptop Charger", "Accessory", "Power & Charging", "65W output, USB-C PD, compact body, laptop and phone support", 290, "charger"],
  ["GaN 100W Fast Charger", "Accessory", "Power & Charging", "100W GaN charger, multiple ports, laptop support, compact design", 520, "charger"],
  ["Universal Laptop Charger 90W", "Accessory", "Power & Charging", "90W output, multi-tip support, voltage protection, laptop ready", 360, "charger"],
  ["Wireless Charging Pad", "Accessory", "Power & Charging", "Qi charging pad, slim body, LED indicator, phone and earbuds support", 190, "charger"],
  ["Surge Protector Extension", "Accessory", "Power & Charging", "Multi-socket extension, surge protection, long cable, switch control", 210, "hub"],
  ["USB-C Braided Cable 1m", "Accessory", "Cables & Adapters", "Braided cable, USB-C charging, data transfer, reinforced tips", 85, "cableBraided"],
  ["Lightning Charging Cable", "Accessory", "Cables & Adapters", "Lightning cable, reinforced jacket, charging and sync support", 95, "cableLightning"],
  ["USB-C to Lightning Cable", "Accessory", "Cables & Adapters", "USB-C to Lightning, fast charging, MFi certified, 1.5m", 120, "cableLightning"],
  ["USB-C Fast Charge Cable 2m", "Accessory", "Cables & Adapters", "USB-C to USB-C, 100W PD support, braided, 2 meter length", 110, "cableUsbC"],
  ["HDMI Cable 2m", "Accessory", "Cables & Adapters", "2m HDMI cable, full HD and 4K support, durable connector", 75, "hub"],
  ["USB-C to HDMI Adapter", "Accessory", "Cables & Adapters", "USB-C input, HDMI output, projector and monitor support", 160, "hub"],
  ["HDMI to VGA Adapter", "Accessory", "Cables & Adapters", "HDMI input, VGA output, projector support, compact adapter", 140, "hub"],
  ["Ethernet USB Adapter", "Accessory", "Cables & Adapters", "USB network adapter, wired internet, compact body, plug-and-play", 190, "hub"],
  ["USB-C 6-in-1 Hub", "Accessory", "Hubs & Docks", "HDMI, USB-A, USB-C, SD card reader, aluminium body", 350, "hub"],
  ["USB-C Docking Station Pro", "Accessory", "Hubs & Docks", "Multi-display dock, Ethernet, HDMI, USB-C PD, office workstation ready", 1450, "hub"],
  ["Thunderbolt 4 Dock", "Accessory", "Hubs & Docks", "Thunderbolt 4, 40Gbps, 3x USB-C, DisplayPort, 96W charging", 3200, "hub"],
  ["256GB USB Flash Drive", "Accessory", "Storage", "256GB storage, USB 3.0 speed, metal body, pocket size", 220, "driveSSD"],
  ["512GB Portable SSD", "Accessory", "Storage", "512GB external SSD, fast transfers, USB-C cable, compact shell", 760, "driveSSD"],
  ["1TB Portable SSD", "Accessory", "Storage", "1TB external SSD, fast backup, shock-resistant body, USB-C", 1180, "driveSSD"],
  ["2TB External Hard Drive", "Accessory", "Storage", "2TB storage, USB 3.0, backup ready, portable enclosure", 890, "hub"],
  ["4TB External Hard Drive", "Accessory", "Storage", "4TB storage, USB 3.0, desktop backup, power adapter included", 1450, "hub"],
  ["NVMe SSD 500GB", "Accessory", "Storage", "500GB internal NVMe SSD, fast boot, laptop upgrade ready", 620, "driveSSD"],
  ["NVMe SSD 1TB", "Accessory", "Storage", "1TB internal NVMe SSD, high-speed storage, laptop upgrade ready", 980, "driveSSD"],
  ["2TB NVMe SSD", "Accessory", "Storage", "2TB NVMe SSD, Gen4 speed, heatsink, desktop and laptop ready", 1850, "driveSSD"],
  ["128GB MicroSD Card", "Accessory", "Storage", "128GB microSD, adapter included, phone and camera support", 130, "hub"],
  ["512GB MicroSD Card", "Accessory", "Storage", "512GB microSD, U3 speed, 4K video, drone and camera ready", 520, "hub"],
  ["LogiStyle Wireless Mouse", "Accessory", "Keyboards & Mice", "Silent clicks, USB receiver, compact shape, long battery", 180, "mouse"],
  ["Ergonomic Vertical Mouse", "Accessory", "Keyboards & Mice", "Vertical grip, wireless connection, adjustable DPI, wrist comfort", 310, "mouse"],
  ["Gaming Mouse RGB", "Accessory", "Keyboards & Mice", "RGB lighting, adjustable DPI, side buttons, braided cable", 360, "mouse"],
  ["Compact Mechanical Keyboard", "Accessory", "Keyboards & Mice", "Mechanical switches, backlight, USB-C cable, compact layout", 430, "keyboard"],
  ["Wireless Keyboard and Mouse Combo", "Accessory", "Keyboards & Mice", "Full-size keyboard, matching mouse, USB receiver, quiet keys", 390, "keyboard"],
  ["Numeric Keypad USB", "Accessory", "Keyboards & Mice", "USB numeric keypad, compact body, plug-and-play support", 180, "keyboard"],
  ["Gaming Mechanical Keyboard", "Accessory", "Keyboards & Mice", "RGB per-key, hot-swap switches, aluminium frame, USB-C", 780, "keyboard"],
  ["Desk Mouse Pad XL", "Accessory", "Desk Setup", "Large desk mat, stitched edges, smooth mouse surface, spill resistance", 160, "desk"],
  ["Universal Laptop Stand", "Accessory", "Desk Setup", "Foldable stand, aluminium body, adjustable angle, ventilation design", 280, "desk"],
  ["Portable Laptop Table", "Accessory", "Desk Setup", "Foldable table, cup slot, tablet groove, bed and sofa support", 450, "desk"],
  ["Ergonomic Laptop Stand", "Accessory", "Desk Setup", "Height-adjustable stand, aluminium, cable management, ventilated", 520, "desk"],
  ["Laptop Cooling Pad", "Accessory", "Cooling & Fans", "Fan-assisted pad, USB power, adjustable height, mesh surface", 230, "fanPad"],
  ["Smart Desk Electric Fan", "Accessory", "Cooling & Fans", "Rechargeable fan, 3 speed levels, USB charging, desk stand", 280, "fanDesk"],
  ["Rechargeable Standing Fan", "Accessory", "Cooling & Fans", "Adjustable height, LED light, 5-hour backup, remote control", 880, "fanStanding"],
  ["Mini USB Neck Fan", "Accessory", "Cooling & Fans", "Wearable fan, rechargeable battery, 3-speed airflow, lightweight body", 160, "fanNeck"],
  ["Tower Cooling Fan", "Accessory", "Cooling & Fans", "Oscillating tower fan, remote control, timer, 3 speed settings", 620, "fanStanding"],
  ["Solar Study Lamp", "Accessory", "Solar & Lighting", "Solar charging, LED desk light, USB phone charging output", 190, "lamp"],
  ["Solar Camping Lantern", "Accessory", "Solar & Lighting", "Foldable lamp, solar panel, emergency light, USB charging", 240, "lamp"],
  ["Solar Home Lighting Kit", "Accessory", "Solar & Lighting", "Solar panel, 3 LED bulbs, phone charging, radio support", 950, "lamp"],
  ["Smart LED Strip 5m", "Accessory", "Solar & Lighting", "RGB lighting, app control, music sync, adhesive backing", 300, "lightStrip"],
  ["Smart LED Bulb", "Accessory", "Solar & Lighting", "Wi-Fi bulb, voice control, dimmable, 16M colours", 140, "lightStrip"],
  ["Adjustable Monitor Arm", "Accessory", "Monitors", "Single monitor arm, clamp mount, tilt and swivel support", 560, "monitor"],
  ["24-inch Office Monitor", "Accessory", "Monitors", "24-inch display, full HD, HDMI input, office productivity", 1350, "monitor"],
  ["27-inch Full HD Monitor", "Accessory", "Monitors", "27-inch display, full HD, HDMI input, entertainment and work", 1850, "monitor"],
  ["27-inch 4K UHD Monitor", "Accessory", "Monitors", "27-inch 4K display, IPS panel, HDMI, DisplayPort, USB-C", 3200, "monitor"],
  ["32-inch Curved Monitor", "Accessory", "Monitors", "32-inch curved display, QHD, 165Hz, gaming and productivity", 4200, "monitor"],
  ["Portable Monitor 15.6-inch", "Accessory", "Monitors", "15.6-inch portable display, USB-C input, travel cover", 2400, "monitor"],
  ["Webcam 1080p", "Accessory", "Creative & Office", "1080p webcam, built-in microphone, privacy cover, USB connection", 380, "webcam"],
  ["4K Webcam", "Accessory", "Creative & Office", "4K webcam, autofocus, built-in ring light, USB-C", 980, "webcam"],
  ["Ring Light with Stand", "Accessory", "Creative & Office", "Adjustable ring light, phone holder, tripod stand, brightness control", 260, "desk"],
  ["Phone Tripod Stand", "Accessory", "Creative & Office", "Adjustable tripod, phone clamp, landscape and portrait support", 210, "phone"],
  ["Content Creator Starter Kit", "Accessory", "Creative & Office", "Tripod, LED light, phone holder, clip microphone, carry pouch", 780, "microphone"],
  ["4K Action Camera", "Accessory", "Creative & Office", "4K video, waterproof case, Wi-Fi transfer, mounting accessories", 2100, "camera"],
  ["DJI Osmo Style Mobile Gimbal", "Accessory", "Creative & Office", "3-axis stabilizer, phone clamp, tracking mode, foldable design", 2400, "phone"],
  ["Graphics Drawing Tablet", "Accessory", "Creative & Office", "Pressure pen, USB connection, drawing surface, shortcut keys", 1250, "tablet"],
  ["Mini Portable Projector", "Accessory", "Creative & Office", "HDMI input, USB media playback, built-in speaker, compact body", 2700, "projector"],
  ["Office Printer All-in-One", "Accessory", "Creative & Office", "Print, scan, copy, Wi-Fi support, refillable ink system", 2900, "printer"],
  ["Thermal Receipt Printer", "Accessory", "Creative & Office", "USB and Bluetooth, 80mm receipts, POS compatible, compact body", 1350, "printer"],
  ["Smart Plug Wi-Fi", "Accessory", "Smart Home", "App control, timer schedules, voice assistant support, 13A rating", 260, "desk"],
  ["Smart Security Camera", "Accessory", "Smart Home", "1080p video, night vision, motion alerts, Wi-Fi connection", 620, "webcam"],
  ["Android TV Box 4K", "Accessory", "Smart Home", "4K output, Wi-Fi, Bluetooth remote, streaming app support", 750, "hub"],
  ["Smart Doorbell Camera", "Accessory", "Smart Home", "1080p doorbell, two-way audio, motion detection, night vision", 980, "webcam"],
  ["Wi-Fi Router AX1800", "Accessory", "Smart Home", "Dual-band Wi-Fi 6, gigabit ports, mesh support, parental controls", 850, "router"],
  ["Wi-Fi Mesh System 3-pack", "Accessory", "Smart Home", "Whole-home Wi-Fi 6, seamless roaming, app management", 2400, "router"],
  ["Phone Screen Protector Pack", "Accessory", "Phone Accessories", "Tempered glass protectors, oleophobic coating, common phone sizes", 70, "phone"],
  ["Universal Phone Case", "Accessory", "Phone Accessories", "Protective case, shock corners, flexible grip, common model support", 90, "phone"],
  ["Tablet Stylus Pen", "Accessory", "Phone Accessories", "Touch stylus, fine tip, note-taking support, tablet compatible", 280, "tablet"],
  ["Phone Grip Stand", "Accessory", "Phone Accessories", "Adhesive phone grip, kickstand, ring holder, universal fit", 65, "phone"],
  ["Samsung Galaxy Tab A9", "Accessory", "Tablets", "8.7-inch tablet, 64GB storage, Wi-Fi, compact media device", 2850, "tablet"],
  ["Lenovo Tab M10", "Accessory", "Tablets", "10-inch display, 128GB storage, stereo speakers, family tablet", 3400, "tablet"],
  ["iPad 10th Gen", "Accessory", "Tablets", "10.9-inch display, A14 chip, 64GB storage, USB-C", 6200, "tablet"],
  ["iPad Air M2", "Accessory", "Tablets", "11-inch Liquid Retina, M2 chip, 128GB, USB-C", 9800, "tablet"],
  ["Laptop RAM 8GB DDR4", "Accessory", "Laptop Parts", "8GB DDR4 memory, laptop upgrade, multitasking improvement", 380, "driveSSD"],
  ["Laptop RAM 16GB DDR4", "Accessory", "Laptop Parts", "16GB DDR4 memory, laptop upgrade, productivity boost", 690, "driveSSD"],
  ["Laptop RAM 32GB DDR4", "Accessory", "Laptop Parts", "32GB DDR4 memory kit, heavy multitasking, workstation ready", 1280, "driveSSD"],
  ["Laptop Battery Replacement", "Accessory", "Laptop Parts", "Replacement battery, common laptop models, capacity tested", 750, "charger"],
  ["Thermal Paste Kit", "Accessory", "Laptop Parts", "Thermal paste, spreader, cleaning wipes, maintenance-ready", 110, "desk"],
  ["Screen Cleaning Kit", "Accessory", "Care & Maintenance", "Microfiber cloth, screen solution, dust brush, phone and laptop safe", 95, "desk"],
  ["USB Wi-Fi Adapter", "Accessory", "Connectivity", "USB wireless adapter, 2.4GHz support, compact dongle, plug-and-play", 170, "hub"],
  ["Bluetooth 5.0 USB Dongle", "Accessory", "Connectivity", "Bluetooth adapter, wireless audio, keyboard and mouse support", 120, "hub"],
  ["Wireless Presenter Remote", "Accessory", "Creative & Office", "Slide remote, laser pointer, USB receiver, presentation controls", 240, "mouse"],
  ["USB-C to 3.5mm Adapter", "Accessory", "Cables & Adapters", "USB-C to headphone jack, DAC chip, compact adapter", 95, "hub"],
  ["Cable Management Box", "Accessory", "Desk Setup", "Cable hiding box, 3 inlets, 2 outlets, wood and plastic finish", 210, "desk"],
  ["VESA Monitor Adapter", "Accessory", "Monitors", "VESA mount plate, 75x75 to 100x100, universal compatibility", 190, "monitor"],
  ["Portable Power Station 300W", "Accessory", "Power & Charging", "300W output, AC outlet, USB-C PD, solar input, camping backup", 5200, "powerStation"],
  ["Smart Water Leak Sensor", "Accessory", "Smart Home", "Wi-Fi water sensor, alarm notification, leak detection", 180, "desk"],
  ["Smart Temperature Sensor", "Accessory", "Smart Home", "Wi-Fi temp and humidity sensor, app monitoring, smart alerts", 160, "desk"],
  ["USB Desk Fan with Light", "Accessory", "Cooling & Fans", "USB fan with LED light, 3-speed, flexible neck, desk clamp", 190, "fanNeck"],
  ["VR Headset", "Accessory", "Smart Home", "Standalone VR, 128GB, hand tracking, immersive gaming", 2400, "vrheadset"],
  ["Fitness Smart Band", "Accessory", "Phone Accessories", "Activity tracker, heart rate, SpO2, sleep tracking, 7-day battery", 380, "smartwatch"],
  ["Smart Watch Pro", "Accessory", "Phone Accessories", "AMOLED display, GPS, health suite, 100+ sports modes", 1200, "smartwatch"],
];

function rowToProduct(row, category) {
  const [name, brandOrCategory, specs, price, imageKey] = row;
  return {
    name,
    brand: category === "Accessory" || category === "Audio" ? undefined : brandOrCategory,
    category,
    subcategory: category === "Accessory" || category === "Audio" ? brandOrCategory : undefined,
    description: specs,
    price,
    image: PRODUCT_IMAGES[imageKey],
  };
}

const LAPTOPS = laptopRows.map((row) => rowToProduct(row, "Laptop"));
const PHONES = phoneRows.map((row) => rowToProduct(row, "Phone"));
const ACCESSORIES = accessoryRows.map(([name, category, subcategory, specs, price, imageKey]) => ({
  name,
  category: "Accessory",
  department: category,
  subcategory,
  description: specs,
  price,
  image: PRODUCT_IMAGES[imageKey],
}));

const LAPTOP_TIERS = [
  ["Student", -0.18, "student bundle, webcam-ready, lightweight setup"],
  ["Office", -0.06, "office bundle, Microsoft Office-ready, reliable battery"],
  ["Pro", 0.12, "professional bundle, upgraded storage, multitasking-ready"],
  ["Creator", 0.26, "creator bundle, colour-focused display, editing-ready"],
  ["Gaming", 0.34, "gaming bundle, cooling stand option, high performance"],
  ["Executive", 0.48, "executive bundle, premium sleeve, priority setup"],
  ["Budget Plus", -0.24, "budget bundle, clean installation, essential apps"],
];

const PHONE_TIERS = [
  ["Essential", -0.16, "starter bundle, screen protector, strong battery"],
  ["Daily", -0.05, "daily-use bundle, case option, social media-ready"],
  ["Plus", 0.1, "extra storage bundle, clear camera, fast charging"],
  ["Pro", 0.24, "premium bundle, camera-focused, smooth display"],
  ["Max", 0.38, "large storage bundle, long battery, performance-ready"],
  ["Business", 0.18, "business bundle, email-ready, secure setup"],
  ["Creator", 0.3, "content bundle, camera-focused, tripod-ready"],
];

const ACCESSORY_TIERS = [
  ["Value", -0.18, "value pack"],
  ["Standard", 0, "standard pack"],
  ["Plus", 0.12, "plus pack"],
  ["Pro", 0.24, "pro pack"],
  ["Max", 0.36, "max pack"],
  ["Student", -0.08, "student pack"],
  ["Business", 0.18, "business pack"],
];

function expandProducts(baseProducts, targetCount, tiers) {
  return Array.from({ length: targetCount }, (_, index) => {
    const base = baseProducts[index % baseProducts.length];
    const tier = tiers[index % tiers.length];
    const cycle = Math.floor(index / baseProducts.length) + 1;
    const priceStep = (cycle % 6) * 45;
    const adjustedPrice = Math.max(50, Math.round((base.price * (1 + tier[1]) + priceStep) / 10) * 10);

    return {
      ...base,
      name: `${base.name} ${tier[0]} ${String(index + 1).padStart(3, "0")}`,
      description: `${base.description}; ${tier[2]}; stock code CH-${String(index + 1).padStart(4, "0")}`,
      price: adjustedPrice,
      sku: `CH-${base.category.toUpperCase().slice(0, 3)}-${String(index + 1).padStart(4, "0")}`,
    };
  });
}

const OS_SERVICE_ROWS = [
  ["Windows 11 Fresh Install", "OS Installation", "Clean Windows 11 installation, driver check, browser setup, updates, and activation support", 180, "desk"],
  ["Windows 10 Install", "OS Installation", "Stable Windows 10 setup for older laptops and office machines", 150, "desk"],
  ["Windows 11 Pro Business Setup", "OS Installation", "Windows 11 Pro install with account setup, BitLocker guidance, and office-ready configuration", 260, "desk"],
  ["Ubuntu Linux Install", "OS Installation", "Ubuntu installation with updates, browser, media apps, and office tools", 160, "server"],
  ["Linux Mint Install", "OS Installation", "Beginner-friendly Linux setup with codecs, office tools, updates, and app store configuration", 160, "server"],
  ["Fedora Workstation Install", "OS Installation", "Modern Linux workstation setup for developers, students, and productivity users", 180, "server"],
  ["Kali Linux Lab Install", "OS Installation", "Security lab installation for learning environments, with update and network tool checks", 220, "server"],
  ["Zorin OS Install", "OS Installation", "Clean Windows-like Linux desktop setup for customers switching from older systems", 170, "server"],
  ["macOS Reinstall Support", "OS Installation", "macOS recovery, clean setup assistance, iCloud guidance, and app readiness checks", 320, "laptopSilver"],
  ["ChromeOS Flex Install", "OS Installation", "Lightweight ChromeOS Flex setup for compatible older laptops and school devices", 150, "laptop"],
  ["Windows + Ubuntu Dual Boot", "OS Installation", "Partition setup for customers who need both Windows and Linux", 280, "server"],
  ["Windows + Kali Dual Boot", "OS Installation", "Dual boot setup for cybersecurity students who need Windows and Kali on one laptop", 320, "server"],
  ["Virtual Machine OS Setup", "OS Installation", "VirtualBox or VMware setup with a guest OS for testing, learning, or isolated workflows", 240, "server"],
  ["Backup Before Installation", "OS Installation", "Basic user-file backup before OS work begins; external drive not included", 120, "driveSSD"],
  ["Boot Repair and OS Recovery", "OS Installation", "Fix boot loops, missing bootloaders, startup errors, and failed update problems", 190, "server"],
  ["Driver and Software Setup", "OS Installation", "Drivers, printer setup, office apps, browser, PDF reader, and media tools", 140, "desk"],
  ["Developer Workstation Setup", "OS Installation", "Code editor, Git, terminal tools, browser, package managers, and development basics", 300, "server"],
];

const OS_SERVICES = OS_SERVICE_ROWS.map(([name, subcategory, specs, price, imageKey], index) => ({
  name,
  category: "Service",
  subcategory,
  description: specs,
  price,
  image: PRODUCT_IMAGES[imageKey],
  sku: `CH-SRV-${String(index + 1).padStart(3, "0")}`,
}));

const LAPTOP_CATALOGUE = expandProducts(LAPTOPS, 500, LAPTOP_TIERS);
const PHONE_CATALOGUE = expandProducts(PHONES, 500, PHONE_TIERS);
const ACCESSORY_CATALOGUE = [
  ...expandProducts(ACCESSORIES, 483, ACCESSORY_TIERS),
  ...OS_SERVICES,
];

const PRODUCTS = [...LAPTOP_CATALOGUE, ...PHONE_CATALOGUE, ...ACCESSORY_CATALOGUE];

const PRODUCT_COUNTS = {
  laptops: LAPTOP_CATALOGUE.length,
  phones: PHONE_CATALOGUE.length,
  accessories: ACCESSORY_CATALOGUE.length,
  total: PRODUCTS.length,
};

function formatCedis(value) {
  return `GH₵ ${Number(value).toLocaleString("en-GH")}`;
}

function checkoutUrl(product) {
  const item = encodeURIComponent(product.name);
  return `checkout.html?item=${item}&price=${product.price}`;
}

function productCard(product) {
  const actionLabel = product.category === "Service" ? "Book" : "Buy";
  return `
    <article class="product-card">
      <img src="${product.image}" alt="${product.name}" />
      <div class="product-body">
        <span class="tag">${product.subcategory || product.brand || product.category}</span>
        <h3>${product.name}</h3>
        <p><span class="spec-label">Specifications:</span> ${product.description}</p>
        <p class="sku-line">${product.sku || "CircuitHouse verified item"}</p>
        <div class="price-row">
          <strong>${formatCedis(product.price)}</strong>
          <a class="button small" href="${checkoutUrl(product)}">${actionLabel}</a>
        </div>
      </div>
    </article>
  `;
}
